allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegedContainer: false
allowedCapabilities: null
apiVersion: v1
fsGroup:
  type: RunAsAny
groups:
- system:cluster-admins
- system:serviceaccounts:pizzaparty-prod
kind: SecurityContextConstraints
metadata:
  annotations:
    kubernetes.io/description: anyuid provides all features of the restricted SCC
      but allows users to run with any UID and any GID.  This is the default SCC for
      authenticated users.
  creationTimestamp: 2016-02-02T00:20:42Z
  name: anyuid
  resourceVersion: "174665"
  selfLink: /api/v1/securitycontextconstraints/anyuid
  uid: cb8eff01-c942-11e5-b92f-2cc26003efa4
priority: 10
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: MustRunAs
supplementalGroups:
  type: RunAsAny
