apiVersion: v1
kind: Service
metadata:
  name: cinder
  labels:
    app: cinder
spec:
  ports:
  - name: cinder-api
    port: 8776
    targetPort: 8776
  #sessionAffinity: ClientIP
  clusterIP: None
  #type: NodePort # Or LoadBalancer in production w/ proper security
  #type: LoadBalancer
  selector:
    app: cinder
