apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs-server
  namespace: openstack2
spec:
  accessModes:
    #- ReadWriteOnce
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
