apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-server
  labels:
    app: pv-nfs-server
spec:
  storageClassName: manual
  claimRef:
    namespace: openstack2
    name: pvc-nfs-server
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  glusterfs:
    endpoints: glusterfs-cluster
    path: gv-nfs
    readOnly: false
  persistentVolumeReclaimPolicy: Retain
